### ISSUE TITLE
设置rime没有候选词

### ISSUE THREAD

**Issue by wpix** [merrickluo/liberime#4]
(setq default-input-method "pyim") 能正常使用
(setq default-input-method 'rime) 时没有候选词

Emacs 的 liberime 部分设置如下：
```
(add-to-list 'load-path "~/liberime/build/")
(require 'liberime)
(liberime-start "/Library/Input Methods/Squirrel.app/Contents/SharedSupport"
		(file-truename "~/.emacs.d/pyim/rime/"))
(liberime-select-schema “double_pinyin_flypy”)
;;(setq pyim-default-scheme 'rime)
```
试过用完整路径代替"~" 但不起作用
同时也有 liberime.so 在 ~/.emacs.d/pyim/rime/ 下。

在 ~/.emacs.d/pyim/rime/default.custom.yaml 里写的是
```
patch:
     schema_list:
         - schema: double_pinyin_flypy
     "menu/page_size": 100
     "speller/auto_select": false
     "speller/auto_select_unique_candidate": false
     "switches/@2/reset" : 1
```
